"use client";
import React from "react";

const House = () => {
  return (
    <img
      className="h-full w-full"
      src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHdpZHRoPSI1MTIiIGhlaWdodD0iNTEyIiB4PSIwIiB5PSIwIiB2aWV3Qm94PSIwIDAgMjQgMjQiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDUxMiA1MTIiIHhtbDpzcGFjZT0icHJlc2VydmUiIGNsYXNzPSIiPjxnPjxwYXRoIGQ9Ik0yMiA1LjcyNFYyYTEgMSAwIDEgMC0yIDB2Mi4zNjZMMTQuNzk3Ljg1NWE0Ljk4IDQuOTggMCAwIDAtNS41OTQgMGwtNyA0LjcyNEE0Ljk5NSA0Ljk5NSAwIDAgMCAwIDkuNzI0VjE5YzAgMi43NTcgMi4yNDMgNSA1IDVoMmExIDEgMCAwIDAgMS0xdi05YzAtLjU1MS40NDgtMSAxLTFoNmMuNTUyIDAgMSAuNDQ5IDEgMXY5YTEgMSAwIDAgMCAxIDFoMmMyLjc1NyAwIDUtMi4yNDMgNS01VjkuNzI0YTQuOTk1IDQuOTk1IDAgMCAwLTItNFoiIGZpbGw9IiMwNDc4NTciIG9wYWNpdHk9IjEiIGRhdGEtb3JpZ2luYWw9IiMwMDAwMDAiIGNsYXNzPSIiPjwvcGF0aD48L2c+PC9zdmc+"
      alt="House Image"
    />
  );
};

export default House;
